"""Branded document generator for Krupp General Contractors.

Branding:
- Primary color: #1B3A5C (navy) — headers, table headers, borders
- Accent color: #D4A84B (gold) — highlights, accents
- Font: Calibri, 11pt body, 14pt headers
- Footer on every page: "Generated by KruppAI | {date} | Review required before distribution"

File naming: {skill}_{project_code}_{date}_{sequence}.{ext}
"""

from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

from docx import Document
from docx.enum.section import WD_ORIENT
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.shared import Cm, Inches, Pt, RGBColor
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side

from kruppai.core.config import Settings

# Branding constants
NAVY = RGBColor(0x1B, 0x3A, 0x5C)
GOLD = RGBColor(0xD4, 0xA8, 0x4B)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
LIGHT_GRAY = RGBColor(0xF2, 0xF2, 0xF2)
FONT_NAME = "Calibri"
BODY_SIZE = Pt(11)
HEADING1_SIZE = Pt(14)
HEADING2_SIZE = Pt(12)

# Excel equivalents
XL_NAVY = "1B3A5C"
XL_GOLD = "D4A84B"
XL_LIGHT_GRAY = "F2F2F2"


@dataclass
class Section:
    """A document section with heading and body content."""

    heading: str
    content: str
    level: int = 1


@dataclass
class TableData:
    """Table data for document output."""

    headers: list[str]
    rows: list[list[str]]
    title: str | None = None
    column_widths: list[float] | None = None


@dataclass
class DocumentContent:
    """Complete document content for output formatting."""

    title: str
    subtitle: str | None = None
    date: str | None = None
    sections: list[Section] = field(default_factory=list)
    tables: list[TableData] = field(default_factory=list)
    header_fields: dict[str, str] = field(default_factory=dict)
    use_letterhead: bool = False


@dataclass
class SpreadsheetContent:
    """Complete spreadsheet content for Excel output."""

    title: str
    sheets: dict[str, TableData] = field(default_factory=dict)


@dataclass
class ProjectInfo:
    """Minimal project info needed for document naming and headers."""

    project_code: str
    name: str
    client_name: str = ""
    address: str = ""


class OutputFormatter:
    """Creates branded DOCX and XLSX documents."""

    def __init__(self, settings: Settings) -> None:
        self.settings = settings
        self.output_dir = settings.output_dir

    def generate_filename(
        self, skill: str, project_code: str, ext: str
    ) -> str:
        """Generate a filename following the convention."""
        today = date.today().isoformat()
        # Find next sequence number
        pattern = f"{skill}_{project_code}_{today}_*.{ext}"
        existing = list(self.output_dir.glob(pattern))
        seq = len(existing) + 1
        return f"{skill}_{project_code}_{today}_{seq:03d}.{ext}"

    def create_docx(
        self,
        content: DocumentContent,
        project: ProjectInfo,
        skill_name: str = "document",
    ) -> Path:
        """Create a branded DOCX document.

        Args:
            content: Document content (sections, tables, headers).
            project: Project information for naming and headers.
            skill_name: Skill name for file naming.

        Returns:
            Path to the generated DOCX file.
        """
        self.output_dir.mkdir(parents=True, exist_ok=True)

        doc = Document()
        style = doc.styles["Normal"]
        style.font.name = FONT_NAME
        style.font.size = BODY_SIZE

        # Configure heading styles
        for level, size in [(1, HEADING1_SIZE), (2, HEADING2_SIZE)]:
            heading_style = doc.styles[f"Heading {level}"]
            heading_style.font.name = FONT_NAME
            heading_style.font.size = size
            heading_style.font.color.rgb = NAVY
            heading_style.font.bold = True

        # Add footer
        section = doc.sections[0]
        footer = section.footer
        footer.is_linked_to_previous = False
        footer_para = footer.paragraphs[0]
        doc_date = content.date or date.today().isoformat()
        footer_para.text = (
            f"Generated by KruppAI | {doc_date} | "
            "Review required before distribution"
        )
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = footer_para.runs[0]
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

        # Letterhead (for client-facing documents)
        if content.use_letterhead:
            p = doc.add_paragraph()
            run = p.add_run("KRUPP GENERAL CONTRACTORS")
            run.font.size = Pt(16)
            run.font.color.rgb = NAVY
            run.font.bold = True
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER

            p = doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p.add_run("General Contractors & Construction Managers")
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

            doc.add_paragraph()  # Spacer

        # Title
        title_para = doc.add_heading(content.title, level=0)
        for run in title_para.runs:
            run.font.color.rgb = NAVY

        # Subtitle
        if content.subtitle:
            p = doc.add_paragraph()
            run = p.add_run(content.subtitle)
            run.font.size = Pt(12)
            run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

        # Header fields (key-value pairs like "Project:", "Date:", etc.)
        if content.header_fields:
            table = doc.add_table(
                rows=len(content.header_fields), cols=2
            )
            table.autofit = True
            for i, (key, value) in enumerate(
                content.header_fields.items()
            ):
                row = table.rows[i]
                cell_key = row.cells[0]
                cell_val = row.cells[1]
                cell_key.text = f"{key}:"
                cell_val.text = value
                for run in cell_key.paragraphs[0].runs:
                    run.font.bold = True
                    run.font.size = BODY_SIZE
            doc.add_paragraph()  # Spacer

        # Sections
        for section_data in content.sections:
            level = min(section_data.level, 2)
            doc.add_heading(section_data.heading, level=level)
            if section_data.content:
                for paragraph_text in section_data.content.split("\n"):
                    if paragraph_text.strip():
                        doc.add_paragraph(paragraph_text.strip())

        # Tables
        for table_data in content.tables:
            if table_data.title:
                doc.add_heading(table_data.title, level=2)

            num_cols = len(table_data.headers)
            table = doc.add_table(
                rows=1 + len(table_data.rows),
                cols=num_cols,
            )
            table.alignment = WD_TABLE_ALIGNMENT.LEFT
            table.style = "Table Grid"

            # Header row
            header_row = table.rows[0]
            for i, header_text in enumerate(table_data.headers):
                cell = header_row.cells[i]
                cell.text = header_text
                for run in cell.paragraphs[0].runs:
                    run.font.bold = True
                    run.font.color.rgb = WHITE
                    run.font.size = BODY_SIZE
                # Navy background
                shading = cell._element.get_or_add_tcPr()
                shading_elm = shading.makeelement(
                    qn("w:shd"),
                    {
                        qn("w:fill"): "1B3A5C",
                        qn("w:val"): "clear",
                    },
                )
                shading.append(shading_elm)

            # Data rows with alternating colors
            for row_idx, row_data in enumerate(table_data.rows):
                row = table.rows[row_idx + 1]
                for col_idx, cell_text in enumerate(row_data):
                    cell = row.cells[col_idx]
                    cell.text = str(cell_text)
                    for run in cell.paragraphs[0].runs:
                        run.font.size = BODY_SIZE
                    # Alternating row shading
                    if row_idx % 2 == 1:
                        shading = cell._element.get_or_add_tcPr()
                        shading_elm = shading.makeelement(
                            qn("w:shd"),
                            {
                                qn("w:fill"): "F2F2F2",
                                qn("w:val"): "clear",
                            },
                        )
                        shading.append(shading_elm)

            doc.add_paragraph()  # Spacer after table

        # Save
        filename = self.generate_filename(
            skill_name, project.project_code, "docx"
        )
        output_path = self.output_dir / filename
        doc.save(str(output_path))
        return output_path

    def create_xlsx(
        self,
        content: SpreadsheetContent,
        project: ProjectInfo,
        skill_name: str = "document",
    ) -> Path:
        """Create a branded XLSX workbook.

        Args:
            content: Spreadsheet content with named sheets.
            project: Project information for naming.
            skill_name: Skill name for file naming.

        Returns:
            Path to the generated XLSX file.
        """
        self.output_dir.mkdir(parents=True, exist_ok=True)

        wb = Workbook()
        # Remove default sheet
        if wb.active:
            wb.remove(wb.active)

        header_font = Font(
            name=FONT_NAME, size=11, bold=True, color="FFFFFF"
        )
        header_fill = PatternFill(
            start_color=XL_NAVY, end_color=XL_NAVY, fill_type="solid"
        )
        alt_fill = PatternFill(
            start_color=XL_LIGHT_GRAY,
            end_color=XL_LIGHT_GRAY,
            fill_type="solid",
        )
        body_font = Font(name=FONT_NAME, size=11)
        thin_border = Border(
            left=Side(style="thin"),
            right=Side(style="thin"),
            top=Side(style="thin"),
            bottom=Side(style="thin"),
        )

        for sheet_name, table_data in content.sheets.items():
            ws = wb.create_sheet(title=sheet_name[:31])  # Excel 31-char limit

            # Headers
            for col_idx, header in enumerate(table_data.headers, start=1):
                cell = ws.cell(row=1, column=col_idx, value=header)
                cell.font = header_font
                cell.fill = header_fill
                cell.border = thin_border
                cell.alignment = Alignment(horizontal="center")

            # Data rows
            for row_idx, row_data in enumerate(table_data.rows, start=2):
                for col_idx, value in enumerate(row_data, start=1):
                    cell = ws.cell(row=row_idx, column=col_idx, value=value)
                    cell.font = body_font
                    cell.border = thin_border
                    if row_idx % 2 == 1:
                        cell.fill = alt_fill

            # Auto-fit column widths (approximation)
            for col_idx in range(1, len(table_data.headers) + 1):
                max_len = len(str(table_data.headers[col_idx - 1]))
                for row_data in table_data.rows:
                    if col_idx - 1 < len(row_data):
                        max_len = max(max_len, len(str(row_data[col_idx - 1])))
                ws.column_dimensions[
                    ws.cell(row=1, column=col_idx).column_letter
                ].width = min(max_len + 4, 50)

            # Auto-filter on headers
            if table_data.headers:
                last_col_letter = ws.cell(
                    row=1, column=len(table_data.headers)
                ).column_letter
                ws.auto_filter.ref = f"A1:{last_col_letter}{len(table_data.rows) + 1}"

        filename = self.generate_filename(
            skill_name, project.project_code, "xlsx"
        )
        output_path = self.output_dir / filename
        wb.save(str(output_path))
        return output_path
