"""Tests for kruppai.core.output_formatter."""

from datetime import date
from pathlib import Path

import pytest
from docx import Document
from openpyxl import load_workbook

from kruppai.core.config import Settings
from kruppai.core.output_formatter import (
    DocumentContent,
    OutputFormatter,
    ProjectInfo,
    Section,
    SpreadsheetContent,
    TableData,
)


@pytest.fixture
def formatter(tmp_settings: Settings) -> OutputFormatter:
    tmp_settings.output_dir.mkdir(parents=True, exist_ok=True)
    return OutputFormatter(tmp_settings)


@pytest.fixture
def project_info() -> ProjectInfo:
    return ProjectInfo(
        project_code="KRUPP-2026-TEST",
        name="City Center Medical Office",
        client_name="Regional Health Partners",
    )


class TestDocxCreation:
    def test_creates_valid_file(
        self, formatter: OutputFormatter, project_info: ProjectInfo
    ) -> None:
        """Generated DOCX opens without error."""
        content = DocumentContent(
            title="Daily Field Report",
            sections=[Section(heading="Work Performed", content="Concrete pour completed.")],
        )
        path = formatter.create_docx(content, project_info, "daily_report")
        assert path.exists()
        assert path.suffix == ".docx"
        # Verify it opens
        doc = Document(str(path))
        assert len(doc.paragraphs) > 0

    def test_has_branding(
        self, formatter: OutputFormatter, project_info: ProjectInfo
    ) -> None:
        """Verify footer text present."""
        content = DocumentContent(
            title="Test Report",
            sections=[Section(heading="Test", content="Content")],
        )
        path = formatter.create_docx(content, project_info)
        doc = Document(str(path))
        footer_text = doc.sections[0].footer.paragraphs[0].text
        assert "Generated by KruppAI" in footer_text
        assert "Review required before distribution" in footer_text

    def test_table_formatting(
        self, formatter: OutputFormatter, project_info: ProjectInfo
    ) -> None:
        """Table has bold headers."""
        content = DocumentContent(
            title="Test",
            tables=[
                TableData(
                    headers=["Trade", "Workers", "Area"],
                    rows=[
                        ["Electrical", "12", "2nd Floor"],
                        ["Mechanical", "8", "3rd Floor"],
                    ],
                )
            ],
        )
        path = formatter.create_docx(content, project_info)
        doc = Document(str(path))
        assert len(doc.tables) == 1
        # Header row cells should have bold text
        header_cell = doc.tables[0].rows[0].cells[0]
        assert header_cell.text == "Trade"

    def test_letterhead_vs_internal(
        self, formatter: OutputFormatter, project_info: ProjectInfo
    ) -> None:
        """use_letterhead=True adds company name block."""
        content = DocumentContent(
            title="Client Letter",
            use_letterhead=True,
            sections=[Section(heading="Update", content="Project is on track.")],
        )
        path = formatter.create_docx(content, project_info)
        doc = Document(str(path))
        full_text = "\n".join(p.text for p in doc.paragraphs)
        assert "KRUPP GENERAL CONTRACTORS" in full_text

    def test_header_fields(
        self, formatter: OutputFormatter, project_info: ProjectInfo
    ) -> None:
        """Header fields rendered as key-value table."""
        content = DocumentContent(
            title="Test",
            header_fields={"Project": "KRUPP-2026-TEST", "Date": "2026-02-13"},
        )
        path = formatter.create_docx(content, project_info)
        doc = Document(str(path))
        assert len(doc.tables) >= 1

    def test_output_directory_creation(
        self, tmp_settings: Settings, project_info: ProjectInfo
    ) -> None:
        """Auto-creates output directory if missing."""
        import shutil
        if tmp_settings.output_dir.exists():
            shutil.rmtree(tmp_settings.output_dir)
        formatter = OutputFormatter(tmp_settings)
        content = DocumentContent(title="Test", sections=[])
        path = formatter.create_docx(content, project_info)
        assert path.exists()


class TestXlsxCreation:
    def test_creates_valid_file(
        self, formatter: OutputFormatter, project_info: ProjectInfo
    ) -> None:
        """Generated XLSX has correct sheets and data."""
        content = SpreadsheetContent(
            title="Punch List",
            sheets={
                "Items": TableData(
                    headers=["#", "Location", "Description"],
                    rows=[
                        ["1", "Room 201", "Ceiling tile misaligned"],
                        ["2", "Room 203", "Paint touch up needed"],
                    ],
                )
            },
        )
        path = formatter.create_xlsx(content, project_info, "punch_list")
        assert path.exists()
        assert path.suffix == ".xlsx"
        wb = load_workbook(str(path))
        assert "Items" in wb.sheetnames
        ws = wb["Items"]
        assert ws.cell(row=1, column=1).value == "#"
        assert ws.cell(row=2, column=2).value == "Room 201"


class TestFilenameConvention:
    def test_filename_format(
        self, formatter: OutputFormatter
    ) -> None:
        """Follows {skill}_{project_code}_{date}_{seq}.{ext} pattern."""
        name = formatter.generate_filename(
            "daily_report", "KRUPP-2026-003", "docx"
        )
        today = date.today().isoformat()
        assert name.startswith(f"daily_report_KRUPP-2026-003_{today}_")
        assert name.endswith(".docx")
        assert "_001." in name

    def test_sequence_increments(
        self,
        formatter: OutputFormatter,
        project_info: ProjectInfo,
    ) -> None:
        """Multiple files get incrementing sequence numbers."""
        content = DocumentContent(title="Test", sections=[])
        path1 = formatter.create_docx(content, project_info, "test_skill")
        path2 = formatter.create_docx(content, project_info, "test_skill")
        assert "_001." in path1.name
        assert "_002." in path2.name
